parameters:
#    invest_share.example.class: Invest\Bundle\ShareBundle\Example

services:
    invest.share.functions:
        class: Invest\Bundle\ShareBundle\Service\Functions
        arguments: [@doctrine]
        calls:
          - [ setContainer, [ @service_container ] ]

    userbundle_service:
        class: FOS\UserBundle\Doctrine\UserManager
        arguments: [@fos_user.user_manager]
